# ВЕКТОРЫ В NUMPY И АРИФМЕТИКА

Произведем сложение двух векторов:

In [1]:
import numpy as np
vec1 = np.array([2,4,7,2.5])
vec2 = np.array([12,6,3.6,13])
vec1 + vec2


array([14. , 10. , 10.6, 15.5])

Что бы произошло при сложении двух списков? Их элементы просто объединились бы в один список:

In [2]:
list1 = [2,4,7,2.5]
list2 = [12,6,3.6,13]
list1 + list2

[2, 4, 7, 2.5, 12, 6, 3.6, 13]

Чтобы сложить два этих списка поэлементно, нам пришлось бы написать списочное сокращение с применением функции zip():

In [3]:
[x + y for x, y in zip(list1, list2)]

[14, 10, 10.6, 15.5]

Для совершения арифметических операций с векторами они должны быть одинаковой длины.

Поэлементно умножим два вектора одинаковой длины:

In [4]:
vec1 = np.array([2, 4, 7, 2.5])
vec2 = np.array([12, 6, 3.6, 13])
vec1 * vec2

array([24. , 24. , 25.2, 32.5])

А теперь создадим vec2, который будет на один элемент короче, чем vec1:

In [5]:
vec1 = np.array([2,4,7,2.5])
vec2 = np.array([12,6,3.6])
#vec1 * vec2

Также векторы можно сравнивать друг с другом поэлементно:

In [6]:
vec1 = np.array([2,4,7,2.5])
vec2 = np.array([12,6,3.6,13])
vec1>vec2

array([False, False,  True, False])

В результате получаем вектор исходной длины из булевых переменных, которые соответствуют результату поэлементного сравнения чисел из двух векторов.

Аналогично можно сравнивать вектор с числом:

In [7]:
vec = np.array([14,15,9,26,53,5,89])
vec <= 26

array([ True,  True,  True,  True, False,  True, False])

# Продвинутые операции с векторами

В курсе алгебры проходят в том числе следующие действия с векторами: вычисление длины (нормы) вектора, нахождение расстояния между векторами, вычисление скалярного произведения. Некоторые из них очень часто используются в машинном обучении, алгоритмах кластеризации и построении математических моделей. Как специалистам в Data Science вам предстоит с этим работать.

Например, ключевые черты лица человека можно представить в виде вектора из чисел. Допустим, что у нас есть база данных всех существующих лиц, представленных в виде векторов. Тогда в идеальном случае, когда мы получим новый вектор с чертами лица, нам будет достаточно найти тот вектор из базы данных, расстояние до которого минимально, чтобы определить человека по лицу.

Посчитаем длину следующего вектора:

In [8]:
vec = np.array([3,4])

Для начала воспользуемся формулой: возведём все элементы в квадрат, посчитаем их сумму, а затем найдём квадратный корень. Найдите все перечисленные операции в данном коде:

In [9]:
lenght = np.sqrt(np.sum(vec ** 2))
print(lenght)

5.0


Но можно было поступить проще. В NumPy есть специальный подмодуль linalg, который позволяет производить операции из линейной алгебры.

Для вычисления длины вектора нам потребуется функция norm:

In [10]:
lenght = np.linalg.norm(vec)
print(lenght)

5.0


Мы получили то же самое расстояние с помощью одного действия!

По сути, расстояние между векторами — это длина такого вектора, который является разностью этих векторов. В самом деле, при вычитании двух векторов вычитаются их соответствующие координаты.

Реализуем вычисление расстояния в коде. Сначала — «сложным» способом напрямую из формулы:

In [11]:
vec1 = np.array([0,3,5])
vec2 = np.array([12,4,7])
distance = np.sqrt(np.sum((vec1 - vec2) **2))
distance

12.206555615733702

А теперь применим более простой способ — используем уже известную нам функцию np.linalg.norm:

In [12]:
vec1 = np.array([0,3,5])
vec2 = np.array([12,4,7])
distance = np.linalg.norm(vec1 - vec2)
distance

12.206555615733702

Наконец, скалярным произведением двух векторов называют сумму произведений их соответствующих координат. 

Реализуем это в коде (по-английски скалярное произведение называют dot — точечный — или scalar product, отсюда и такое название переменной):

In [13]:
vec1 = np.arange(1,6)
vec2 = np.linspace(10,20,5)
scalar_product = np.sum(vec1 * vec2)
scalar_product

250.0

Наверное, вы уже догадались, что в NumPy есть множество встроенных функций, поэтому возник резонный вопрос: можно ли проще и вообще без формул?

Да! Для этого используют функцию np.dot(x, y):

In [14]:
scalar_product = np.dot(vec1, vec2)
scalar_product

250.0

Скалярное произведение также имеет широкое применение в математике и других операциях с векторами. В частности, равенство скалярного произведения нулю означает перпендикулярность рассматриваемых векторов:

In [15]:
x = np.array([25, 0])
y = np.array([0, 10])
np.dot(x,y)

0

Здесь были специально заданы векторы, параллельные осям  и  (так как одна из координат в них равна нулю). Они перпендикулярны, как перпендикулярны соответствующие оси, а скалярное произведение действительно равно нулю.

В целом, скалярное произведение часто используется для определения угла между векторами.

    БАЗОВЫЕ СТАТИСТИЧЕСКИЕ ФУНКЦИИ ДЛЯ ВЕКТОРОВ

Функции np.min и np.max позволяют находить максимальное и минимальное значение в векторе. Их можно записывать как в виде np.min(<vector>), так и в виде <vector>.min():

In [16]:
vec = np.array([2,7,18,28,18,1,8,4])
vec.min()
np.max(vec)

28

Функция mean позволяет посчитать среднее значение. Больше не требуется реализовывать её «руками»!

In [17]:
vec.mean()

10.75