                МАССИВЫ В NUMPY

СОЗДАНИЕ МАССИВА ИЗ СПИСКА

In [1]:
import numpy as np
arr = np.array([1,5,2,9,10])
arr
#array([ 1,  5,  2,  9, 10])


array([ 1,  5,  2,  9, 10])

Функция np.array возвращает объекты типа numpy.ndarray:

In [2]:
print(type(arr))
#<class 'numpy.ndarray'>

<class 'numpy.ndarray'>


Давайте теперь создадим двумерный массив из списка списков. Его также можно назвать таблицей чисел или матрицей. Сделаем это с помощью той же функции np.array():

In [3]:
nd_arr = np.array([
                [12,45,78],
                [34,56,13],
                [12,98,76]
                ])
nd_arr

array([[12, 45, 78],
       [34, 56, 13],
       [12, 98, 76]])

ТИПЫ ДАННЫХ В МАССИВЕ

In [4]:
arr = np.array([1,5,2,9,10])
arr.dtype
#dtype('int32')

dtype('int64')

 Задать тип данных сразу при создании массива можно с помощью параметра dtype:

In [5]:
arr = np.array([1,5,2,9,10], dtype=np.int8)
arr
#array([ 1,  5,  2,  9, 10], dtype=int8)

array([ 1,  5,  2,  9, 10], dtype=int8)

Теперь, если добавить в arr число больше 127 или меньше -128, оно потеряет исходное значение, как и при преобразовании к меньшему типу:

In [6]:
#arr[2] = 2000
arr
# array([  1,   5, -48,   9,  10], dtype=int8)

array([ 1,  5,  2,  9, 10], dtype=int8)

Если добавить float в массив int, пропадёт десятичная часть:

In [7]:
arr[2] = 125.5
arr
#array([  1,   5, 125,   9,  10], dtype=int8)

array([  1,   5, 125,   9,  10], dtype=int8)

Строку, которую можно преобразовать в число, можно сразу положить в массив. Она будет приведена к нужному типу автоматически:

In [8]:
arr[2] = '12'
arr
#array([ 1,  5, 12,  9, 10], dtype=int8)

array([ 1,  5, 12,  9, 10], dtype=int8)

А вот при попытке положить в массив строку, которую нельзя преобразовать в число, возникнет ошибка:

In [9]:
#arr[2] = 'test'
#ValueError: invalid literal for int() with base 10: 'test'

Поменять тип данных во всём массиве можно с помощью тех же функций, которыми мы пользовались для преобразования типов отдельных переменных в предыдущем юните (например, np.int32 или np.float128):

In [10]:
#arr = np.float128(arr)
arr = np.float32(arr)
arr

array([ 1.,  5., 12.,  9., 10.], dtype=float32)

При преобразовании типов данных в массиве не забывайте о том, что часть чисел может потерять смысл, если менять тип данных с более ёмкого на менее ёмкий:

In [11]:
arr = np.array([12321, -1234, 3435, -214, 100], dtype=np.int32)
arr
#array([12321, -1234,  3435,  -214,   100])

arr = np.uint8(arr)
arr

array([ 33,  46, 107,  42, 100], dtype=uint8)

Все числа, кроме 100, не могли быть корректно представлены в формате uint8, поэтому они отличаются от того, что ожидалось.

СВОЙСТВА NUMPY-МАССИВОВ

Вы уже узнали, как получить тип данных, который хранится в массиве. Сделать это можно с помощью атрибута dtype. Есть и другие свойства массивов, которые будет полезно узнать.

Будем тренироваться на массивах arr и nd_arr:

In [12]:
arr = np.array([1,5,2,9,10], dtype=np.int8)
nd_arr = np.array([
                    [12,45,78],
                    [34,56,13],
                    [12,98,76]
                    ], dtype=np.int16)

1. Узнать размерность массива можно с помощью .ndim:

In [13]:
arr.ndim
#1
nd_arr.ndim
#2

2

2. Узнать общее число элементов в массиве можно с помощью .size:

In [14]:
arr.size
#5
nd_arr.size
#9

9

3. Форма или структура массива хранится в атрибуте .shape:

In [15]:
arr.shape

nd_arr.shape

(3, 3)

4. Наконец, узнать, сколько «весит» каждый элемент массива в байтах позволяет .itemsize:

In [16]:
arr.itemsize
nd_arr.itemsize

2

ЗАПОЛНЕНИЕ НОВЫХ МАССИВОВ

→ Не всегда значения, которые будут храниться в массиве, уже доступны, а иметь для них массив уже хочется.

Можно заранее подготовить массив заданной размерности, заполненный нулями, а потом загружать в него реальные данные по мере необходимости.

Массив из нулей создаётся функцией np.zeros. Она принимает аргументы shape (обязательный) — форма массива (одно число или кортеж) и dtype (необязательный) — тип данных, который будет храниться в массиве.

Создадим одномерный массив из пяти элементов:

In [17]:
zeros_1d = np.zeros(5)
zeros_1d
#array([0., 0., 0., 0., 0.])

array([0., 0., 0., 0., 0.])

Создадим трёхмерный массив с формой 5x4x3 и типом float32:

In [18]:
zeros_3d = np.zeros((5,4,3), dtype=np.float32)
#zeros_3d
print(zeros_3d.shape)

(5, 4, 3)


Ещё одной удобной функцией для создания одномерных массивов является arange. Она аналогична встроенной функции range, но обладает рядом особенностей. Вот её сигнатура: arange([start,] stop, [step,], dtype=None).

Аргументы start (по умолчанию 0), step (по умолчанию 1) и dtype (определяется автоматически) являются необязательными:

start (входит в диапазон возвращаемых значений) задаёт начальное число;
stop (не входит в диапазон возвращаемых значений, как и при использовании range) задаёт правую границу диапазона;
step задаёт шаг, с которым в массив добавляются новые значения.
В отличие от range, в функции arange все перечисленные параметры могут иметь тип float.

Поэкспериментируем. Создадим массив из пяти чисел от 0 до 4:

In [19]:
np.arange(5)
#array([0, 1, 2, 3, 4])

array([0, 1, 2, 3, 4])

Создадим массив от 2.5 до 5:

In [20]:
np.arange(2.5, 5)
#array([2.5, 3.5, 4.5])

array([2.5, 3.5, 4.5])

Создадим массив от 2.5 до 5 с шагом 0.5:

In [21]:
np.arange(2.5, 5, 0.5)
#array([2.5, 3. , 3.5, 4. , 4.5])

array([2.5, 3. , 3.5, 4. , 4.5])

Создадим массив от 2.5 до 5 с шагом 0.5 и с типом float16:

In [22]:
np.arange(2.5, 5, 0.5, dtype=np.float16)
#array([2.5, 3. , 3.5, 4. , 4.5], dtype=float16)

array([2.5, 3. , 3.5, 4. , 4.5], dtype=float16)

На самом деле операции с плавающей точкой не всегда бывают предсказуемыми из-за особенностей хранения таких чисел в памяти компьютера. Поэтому для работы с дробными параметрами start, stop и step лучше использовать функцию linspace (англ. linear space — линейное пространство). Она тоже возвращает одномерный массив из чисел, расположенных на равном удалении друг от друга между началом и концом диапазона, но обладает немного другим поведением и сигнатурой:

np.linspace(start, stop, num=50, endpoint=True, retstep=False, dtype=None)

In [23]:
arr = np.linspace(1, 2,11)
arr

array([1. , 1.1, 1.2, 1.3, 1.4, 1.5, 1.6, 1.7, 1.8, 1.9, 2. ])

Создадим массив из десяти чисел между 1 и 2, не включая 2:

In [24]:
arr = np.linspace(1,2,10, endpoint=False)
arr

array([1. , 1.1, 1.2, 1.3, 1.4, 1.5, 1.6, 1.7, 1.8, 1.9])

Узнаем, какой шаг был использован для создания массива из десяти чисел между 1 и 2, где 2 включалось и не включалось:

In [25]:
arr, step = np.linspace(1, 2, 10, endpoint=True, retstep=True)
print(step)
# 0.1111111111111111

arr, step = np.linspace(1, 2, 10, endpoint=False, retstep=True)
print(step)
# 0.1


0.1111111111111111
0.1


→ Функцию linspace очень удобно использовать при построении графиков различных функций, поскольку она позволяет получить равномерный массив чисел, к которому можно применить исследуемую функцию и показать результат на графике. Вы научитесь это делать в модуле, посвящённом визуализации.

In [26]:
arr, step = np.linspace(-6, 21, 60, retstep=True)
arr
print(step)


0.4576271186440678


In [27]:
arr, step = np.linspace(-6, 21, 60, endpoint=False, retstep=True)
arr
step

0.45

           ДЕЙСТВИЯ С МАССИВАМИ 

ИЗМЕНЕНИЕ ФОРМЫ МАССИВА

Создадим массив из восьми чисел:

In [28]:
import numpy as np
arr = np.arange(8)
arr

array([0, 1, 2, 3, 4, 5, 6, 7])

Поменять форму массива arr можно с помощью присвоения атрибуту shape кортежа с желаемой формой:

In [29]:
arr.shape = (2,4)
arr

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

Чтобы оставить исходный массив без изменений и дополнительно получить новый массив новой формы, нужно использовать функцию reshape. Она также принимает в качестве аргумента кортеж из чисел для формы, но возвращает новый массив, а не изменяет исходный:

In [30]:
arr = np.arange(8)
arr_new = arr.reshape((2, 4))
arr_new

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [31]:
arr = np.arange(8)
arr_new = arr.reshape((2, 4), order='F')
arr_new

array([[0, 2, 4, 6],
       [1, 3, 5, 7]])

Ещё одной часто используемой операцией с формой массива (особенно двумерного) является транспонирование. Эта операция меняет строки и столбцы массива местами. В NumPy эту операцию совершает функция transpose.

Будем работать с двумерным массивом:

In [32]:
arr = np.arange(8)
arr.shape = (2, 4)
arr

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

Транспонируем его:

In [33]:
arr_trans = arr.transpose()
arr_trans

array([[0, 4],
       [1, 5],
       [2, 6],
       [3, 7]])

При транспонировании одномерного массива его форма не меняется:

In [34]:
arr = np.arange(3)
print(arr.shape)
arr_trans = arr.transpose()
print(arr_trans.shape)

(3,)
(3,)


            ИНДЕКСЫ И СРЕЗЫ В МАССИВАХ

В определении массива указано, что он позволяет быстро получать элементы по индексу. Как же это происходит?

Создадим массив из шести чисел:

In [35]:
arr = np.linspace(1,2,6)
arr

array([1. , 1.2, 1.4, 1.6, 1.8, 2. ])

Обратиться к его элементу по индексу можно так же, как и к списку:

In [36]:
print(arr[2])

1.4


Привычная запись для срезов работает и для одномерных массивов:

In [37]:
print(arr[2:4])

[1.4 1.6]


Наконец, напечатать массив в обратном порядке можно с помощью привычной конструкции [::-1]:

In [38]:
print(arr[::-1])

[2.  1.8 1.6 1.4 1.2 1. ]


С многомерными массивами работать немного интереснее. Создадим двумерный массив из одномерного:

In [39]:
nd_array = np.linspace(0,6,12,  endpoint=False).reshape(3,4)
nd_array

array([[0. , 0.5, 1. , 1.5],
       [2. , 2.5, 3. , 3.5],
       [4. , 4.5, 5. , 5.5]])

Можно воспользоваться привычной записью нескольких индексов в нескольких квадратных скобках:

In [40]:
nd_array[1][2]

3.0

Как видите, получилось то же самое число. Также через запятую можно передавать срезы или даже их комбинации с индексами. Например, получим все элементы из колонки 3 для первых двух строк:

In [41]:
nd_array[:2, 2]

array([1., 3.])

Несмотря на то что в массиве этот срез является столбцом, вместо него мы получили одномерный массив в виде строки.

Можно применять срезы сразу и к строкам, и к столбцам:

In [42]:
nd_array[1:, 2:4]

array([[3. , 3.5],
       [5. , 5.5]])

Чтобы получить все значения из какой-то оси, можно оставить на её месте двоеточие. Например, из всех строк получим срез с третьего по четвёртый столбцы:

In [43]:
nd_array[:, 2:4]

array([[1. , 1.5],
       [3. , 3.5],
       [5. , 5.5]])

Чтобы получить самую последнюю ось (в данном случае все столбцы), двоеточие писать необязательно. Строки будут получены целиком по умолчанию:

In [44]:
nd_array[:2]

array([[0. , 0.5, 1. , 1.5],
       [2. , 2.5, 3. , 3.5]])

In [45]:
mystery = np.array([[-13586,  15203,  28445, -27117,  -1781, -17182, -18049],
       [ 25936, -30968,  -1297,  -4593,   6451,  15790,   7181],
       [ 13348,  28049,  28655,  -6012,  21762,  25397,   8225],
       [ 13240,   7994,  32592,  20149,  13754,  11795,   -564],
       [-21725,  -8681,  30305,  22260, -17918,  12578,  29943],
       [-16841, -25392, -17278,  11740,   5916,    -47, -32037]],
      dtype=np.int16)

In [46]:
elem_5_3 = mystery[4, 2]
elem_5_3

30305

In [47]:
last = mystery[-1,-1]
last

-32037

In [48]:
line_4 = mystery[3]
line_4

array([13240,  7994, 32592, 20149, 13754, 11795,  -564], dtype=int16)

In [49]:
col_2 = mystery[:,-2]
col_2

array([-17182,  15790,  25397,  11795,  12578,    -47], dtype=int16)

In [50]:
part = mystery[1:4, 2:5]
part

array([[-1297, -4593,  6451],
       [28655, -6012, 21762],
       [32592, 20149, 13754]], dtype=int16)

In [51]:
rev = mystery [::-1, -1]
rev

array([-32037,  29943,   -564,   8225,   7181, -18049], dtype=int16)

In [52]:
trans = mystery.transpose()
trans

array([[-13586,  25936,  13348,  13240, -21725, -16841],
       [ 15203, -30968,  28049,   7994,  -8681, -25392],
       [ 28445,  -1297,  28655,  32592,  30305, -17278],
       [-27117,  -4593,  -6012,  20149,  22260,  11740],
       [ -1781,   6451,  21762,  13754, -17918,   5916],
       [-17182,  15790,  25397,  11795,  12578,    -47],
       [-18049,   7181,   8225,   -564,  29943, -32037]], dtype=int16)

СОРТИРОВКА ОДНОМЕРНЫХ МАССИВОВ

Иногда возникает задача по сортировке значений в массиве. Для её решения существуют встроенная в NumPy функция sort. Она обладает дополнительными параметрами, в том числе возможностью сортировки многомерных массивов, однако пока что это нам не потребуется. Применять функцию можно двумя способами.

Способ 1. Функция np.sort(<массив>) возвращает новый отсортированный массив:

In [53]:
arr = np.array([23,12,45,12,23,4,15,3])
arr_new = np.sort(arr)
print(arr)
# [23 12 45 12 23  4 15  3]
print(arr_new)
# [ 3  4 12 12 15 23 23 45]

[23 12 45 12 23  4 15  3]
[ 3  4 12 12 15 23 23 45]


Способ 2. Функция <массив>.sort() сортирует исходный массив и возвращает None:

In [54]:
arr = np.array([23,12,45,12,23,4,15,3])
print(arr.sort())
# None
print(arr)
# [ 3  4 12 12 15 23 23 45]

None
[ 3  4 12 12 15 23 23 45]


РАБОТА С ПРОПУЩЕННЫМИ ДАННЫМИ

Начнём с примера — создадим массив:

In [55]:
data = np.array([4,9,-4,3])

Воспользуемся встроенной в NumPy функцией sqrt, чтобы посчитать квадратные корни из элементов.

In [56]:
roots = np.sqrt(data)
roots

/var/folders/57/vt6bjgsj20s5w24_t64kcflh0000gn/T/ipykernel_2930/3752651322.py:1: RuntimeWarning: invalid value encountered in sqrt
  roots = np.sqrt(data)


array([2.        , 3.        ,        nan, 1.73205081])

NumPy выдал предупреждение о том, что в функцию sqrt попало некорректное значение. Это было число -4, а как вы помните, корень из отрицательного числа в действительных числах не берётся. Однако программа не сломалась окончательно, а продолжила работу. На том месте, где должен был оказаться корень из -4, теперь присутствует объект nan. Он расшифровывается как Not a number (не число). Этот объект аналогичен встроенному типу None, но имеет несколько отличий:

Отличие 1. None является отдельным объектом типа NoneType. np.nan — это отдельный представитель класса float:

In [57]:
print(type(None))
# <class 'NoneType'>
print(type(np.nan))
# <class 'float'>
type(np.nan)

<class 'NoneType'>
<class 'float'>


float

Отличие 2. None могут быть равны друг другу, а np.nan — нет:

In [58]:
print(None == None)
# True
print(np.nan == np.nan)
# False

True
False


Как вы помните, чтобы грамотно сравнить что-либо с None, необходимо использовать оператор is. Это ещё более актуально для np.nan. Однако None даже через is не является эквивалентным np.nan:

In [59]:
print(None is None)
# True
print(np.nan is np.nan)
# True
print(np.nan is None)
# False

True
True
False


Иногда работать с отсутствующими данными всё же нужно. Они могут возникнуть не только потому, что мы применили функцию к некорректному аргументу. Например, при анализе вакансий на сайте для некоторых из них может быть не указана зарплата, но при этом нам необходимо проанализировать статистику по зарплатам на сайте. Если попробовать посчитать сумму массива, который содержит np.nan, в итоге получится nan:

In [60]:
sum(roots)

nan

??? Что же делать?

Можно заполнить пропущенные значения, например, нулями. Для этого с помощью функции np.isnan(<массив>) узнаем, на каких местах в массиве находятся «не числа»:

In [61]:
np.isnan(roots)
# array([False, False,  True, False])

array([False, False,  True, False])

Можно использовать полученный массив из True и False для извлечения элементов из массива roots, на месте которых в булевом массиве указано True. Таким способом можно узнать сами элементы, которые удовлетворяют условию np.isnan:


In [62]:
roots[np.isnan(roots)]
# array([nan])

array([nan])

Этим элементам можно присвоить новые значения, например 0:

In [63]:
roots[np.isnan(roots)] = 0
roots
# array([2.        , 3.        , 0.        , 1.73205081])

array([2.        , 3.        , 0.        , 1.73205081])

После этого, если пропущенных значений больше нет, можем подсчитать сумму элементов массива:


In [64]:
sum(roots)
# 6.732050807568877

6.732050807568877

Ранее проблема при подсчёте суммы элементов в массиве roots возникала из-за того, что отсутствовало значение для квадратного корня из -4 — вместо него было указано np.nan. Сумма элементов массива, содержащего nan, также является nan. Поэтому приходится заменить nan, например, на 0, чтобы подсчитать сумму элементов массива.

# Задание 7.4

In [65]:
mystery = np.array([ 12279., -26024.,  28745.,  np.nan,  31244.,  -2365.,  -6974.,
        -9212., np.nan, -17722.,  16132.,  25933.,  np.nan, -16431.,
        29810.], dtype=np.float32)

In [66]:
nans_index = np.isnan(mystery)
nans_index

array([False, False, False,  True, False, False, False, False,  True,
       False, False, False,  True, False, False])

In [67]:
n_nan = sum(nans_index)
n_nan

3

In [68]:
mystery_new = mystery.copy()
mystery_new[nans_index] = 0
mystery_new

array([ 12279., -26024.,  28745.,      0.,  31244.,  -2365.,  -6974.,
        -9212.,      0., -17722.,  16132.,  25933.,      0., -16431.,
        29810.], dtype=float32)

In [69]:
mystery_int = np.int32(mystery)
mystery_int

/var/folders/57/vt6bjgsj20s5w24_t64kcflh0000gn/T/ipykernel_2930/4116977587.py:1: RuntimeWarning: invalid value encountered in cast
  mystery_int = np.int32(mystery)


array([ 12279, -26024,  28745,      0,  31244,  -2365,  -6974,  -9212,
            0, -17722,  16132,  25933,      0, -16431,  29810],
      dtype=int32)

In [70]:
array = np.sort(mystery)
array

array([-26024., -17722., -16431.,  -9212.,  -6974.,  -2365.,  12279.,
        16132.,  25933.,  28745.,  29810.,  31244.,     nan,     nan,
           nan], dtype=float32)

In [71]:
table = array.reshape((5,3), order ='F')
table

array([[-26024.,  -2365.,  29810.],
       [-17722.,  12279.,  31244.],
       [-16431.,  16132.,     nan],
       [ -9212.,  25933.,     nan],
       [ -6974.,  28745.,     nan]], dtype=float32)

In [72]:
col = table[:,1]
col

array([-2365., 12279., 16132., 25933., 28745.], dtype=float32)