                МАССИВЫ В NUMPY

СОЗДАНИЕ МАССИВА ИЗ СПИСКА

In [1]:
import numpy as np
arr = np.array([1,5,2,9,10])
arr
#array([ 1,  5,  2,  9, 10])


array([ 1,  5,  2,  9, 10])

Функция np.array возвращает объекты типа numpy.ndarray:

In [2]:
print(type(arr))
#<class 'numpy.ndarray'>

<class 'numpy.ndarray'>


Давайте теперь создадим двумерный массив из списка списков. Его также можно назвать таблицей чисел или матрицей. Сделаем это с помощью той же функции np.array():

In [3]:
nd_arr = np.array([
                [12,45,78],
                [34,56,13],
                [12,98,76]
                ])
nd_arr

array([[12, 45, 78],
       [34, 56, 13],
       [12, 98, 76]])

ТИПЫ ДАННЫХ В МАССИВЕ

In [4]:
arr = np.array([1,5,2,9,10])
arr.dtype
#dtype('int32')

dtype('int32')

 Задать тип данных сразу при создании массива можно с помощью параметра dtype:

In [5]:
arr = np.array([1,5,2,9,10], dtype=np.int8)
arr
#array([ 1,  5,  2,  9, 10], dtype=int8)

array([ 1,  5,  2,  9, 10], dtype=int8)

Теперь, если добавить в arr число больше 127 или меньше -128, оно потеряет исходное значение, как и при преобразовании к меньшему типу:

In [6]:
#arr[2] = 2000
arr
# array([  1,   5, -48,   9,  10], dtype=int8)

array([ 1,  5,  2,  9, 10], dtype=int8)

Если добавить float в массив int, пропадёт десятичная часть:

In [7]:
arr[2] = 125.5
arr
#array([  1,   5, 125,   9,  10], dtype=int8)

array([  1,   5, 125,   9,  10], dtype=int8)

Строку, которую можно преобразовать в число, можно сразу положить в массив. Она будет приведена к нужному типу автоматически:

In [8]:
arr[2] = '12'
arr
#array([ 1,  5, 12,  9, 10], dtype=int8)

array([ 1,  5, 12,  9, 10], dtype=int8)

А вот при попытке положить в массив строку, которую нельзя преобразовать в число, возникнет ошибка:

In [9]:
#arr[2] = 'test'
#ValueError: invalid literal for int() with base 10: 'test'

Поменять тип данных во всём массиве можно с помощью тех же функций, которыми мы пользовались для преобразования типов отдельных переменных в предыдущем юните (например, np.int32 или np.float128):

In [10]:
#arr = np.float128(arr)
arr = np.float32(arr)
arr

array([ 1.,  5., 12.,  9., 10.], dtype=float32)

При преобразовании типов данных в массиве не забывайте о том, что часть чисел может потерять смысл, если менять тип данных с более ёмкого на менее ёмкий:

In [11]:
arr = np.array([12321, -1234, 3435, -214, 100], dtype=np.int32)
arr
#array([12321, -1234,  3435,  -214,   100])

arr = np.uint8(arr)
arr

array([ 33,  46, 107,  42, 100], dtype=uint8)

Все числа, кроме 100, не могли быть корректно представлены в формате uint8, поэтому они отличаются от того, что ожидалось.

СВОЙСТВА NUMPY-МАССИВОВ

Вы уже узнали, как получить тип данных, который хранится в массиве. Сделать это можно с помощью атрибута dtype. Есть и другие свойства массивов, которые будет полезно узнать.

Будем тренироваться на массивах arr и nd_arr:

In [12]:
arr = np.array([1,5,2,9,10], dtype=np.int8)
nd_arr = np.array([
                    [12,45,78],
                    [34,56,13],
                    [12,98,76]
                    ], dtype=np.int16)

1. Узнать размерность массива можно с помощью .ndim:

In [13]:
arr.ndim
#1
nd_arr.ndim
#2

2

2. Узнать общее число элементов в массиве можно с помощью .size:

In [14]:
arr.size
#5
nd_arr.size
#9

9

3. Форма или структура массива хранится в атрибуте .shape:

In [15]:
arr.shape

nd_arr.shape

(3, 3)

4. Наконец, узнать, сколько «весит» каждый элемент массива в байтах позволяет .itemsize:

In [16]:
arr.itemsize
nd_arr.itemsize

2

ЗАПОЛНЕНИЕ НОВЫХ МАССИВОВ

→ Не всегда значения, которые будут храниться в массиве, уже доступны, а иметь для них массив уже хочется.

Можно заранее подготовить массив заданной размерности, заполненный нулями, а потом загружать в него реальные данные по мере необходимости.

Массив из нулей создаётся функцией np.zeros. Она принимает аргументы shape (обязательный) — форма массива (одно число или кортеж) и dtype (необязательный) — тип данных, который будет храниться в массиве.

Создадим одномерный массив из пяти элементов:

In [17]:
zeros_1d = np.zeros(5)
zeros_1d
#array([0., 0., 0., 0., 0.])

array([0., 0., 0., 0., 0.])

Создадим трёхмерный массив с формой 5x4x3 и типом float32:

In [21]:
zeros_3d = np.zeros((5,4,3), dtype=np.float32)
#zeros_3d
print(zeros_3d.shape)

(5, 4, 3)


Ещё одной удобной функцией для создания одномерных массивов является arange. Она аналогична встроенной функции range, но обладает рядом особенностей. Вот её сигнатура: arange([start,] stop, [step,], dtype=None).

Аргументы start (по умолчанию 0), step (по умолчанию 1) и dtype (определяется автоматически) являются необязательными:

start (входит в диапазон возвращаемых значений) задаёт начальное число;
stop (не входит в диапазон возвращаемых значений, как и при использовании range) задаёт правую границу диапазона;
step задаёт шаг, с которым в массив добавляются новые значения.
В отличие от range, в функции arange все перечисленные параметры могут иметь тип float.

Поэкспериментируем. Создадим массив из пяти чисел от 0 до 4:

In [22]:
np.arange(5)
#array([0, 1, 2, 3, 4])

array([0, 1, 2, 3, 4])

Создадим массив от 2.5 до 5:

In [24]:
np.arange(2.5, 5)
#array([2.5, 3.5, 4.5])

array([2.5, 3.5, 4.5])

Создадим массив от 2.5 до 5 с шагом 0.5:

In [25]:
np.arange(2.5, 5, 0.5)
#array([2.5, 3. , 3.5, 4. , 4.5])

array([2.5, 3. , 3.5, 4. , 4.5])

Создадим массив от 2.5 до 5 с шагом 0.5 и с типом float16:

In [27]:
np.arange(2.5, 5, 0.5, dtype=np.float16)
#array([2.5, 3. , 3.5, 4. , 4.5], dtype=float16)

array([2.5, 3. , 3.5, 4. , 4.5], dtype=float16)

На самом деле операции с плавающей точкой не всегда бывают предсказуемыми из-за особенностей хранения таких чисел в памяти компьютера. Поэтому для работы с дробными параметрами start, stop и step лучше использовать функцию linspace (англ. linear space — линейное пространство). Она тоже возвращает одномерный массив из чисел, расположенных на равном удалении друг от друга между началом и концом диапазона, но обладает немного другим поведением и сигнатурой:

np.linspace(start, stop, num=50, endpoint=True, retstep=False, dtype=None)

In [37]:
arr = np.linspace(1, 2,11)
arr

array([1. , 1.1, 1.2, 1.3, 1.4, 1.5, 1.6, 1.7, 1.8, 1.9, 2. ])

Создадим массив из десяти чисел между 1 и 2, не включая 2:

In [36]:
arr = np.linspace(1,2,10, endpoint=False)
arr

array([1. , 1.1, 1.2, 1.3, 1.4, 1.5, 1.6, 1.7, 1.8, 1.9])

Узнаем, какой шаг был использован для создания массива из десяти чисел между 1 и 2, где 2 включалось и не включалось:

In [38]:
arr, step = np.linspace(1, 2, 10, endpoint=True, retstep=True)
print(step)
# 0.1111111111111111

arr, step = np.linspace(1, 2, 10, endpoint=False, retstep=True)
print(step)
# 0.1


0.1111111111111111
0.1


→ Функцию linspace очень удобно использовать при построении графиков различных функций, поскольку она позволяет получить равномерный массив чисел, к которому можно применить исследуемую функцию и показать результат на графике. Вы научитесь это делать в модуле, посвящённом визуализации.

In [46]:
arr, step = np.linspace(-6, 21, 60, retstep=True)
arr
print(step)


0.4576271186440678


In [48]:
arr, step = np.linspace(-6, 21, 60, endpoint=False, retstep=True)
arr
step

0.45

           ДЕЙСТВИЯ С МАССИВАМИ 

ИЗМЕНЕНИЕ ФОРМЫ МАССИВА

Создадим массив из восьми чисел:

In [49]:
import numpy as np
arr = np.arange(8)
arr

array([0, 1, 2, 3, 4, 5, 6, 7])

Поменять форму массива arr можно с помощью присвоения атрибуту shape кортежа с желаемой формой:

In [50]:
arr.shape = (2,4)
arr

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

Чтобы оставить исходный массив без изменений и дополнительно получить новый массив новой формы, нужно использовать функцию reshape. Она также принимает в качестве аргумента кортеж из чисел для формы, но возвращает новый массив, а не изменяет исходный:

In [51]:
arr = np.arange(8)
arr_new = arr.reshape((2, 4))
arr_new

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [52]:
arr = np.arange(8)
arr_new = arr.reshape((2, 4), order='F')
arr_new

array([[0, 2, 4, 6],
       [1, 3, 5, 7]])

Ещё одной часто используемой операцией с формой массива (особенно двумерного) является транспонирование. Эта операция меняет строки и столбцы массива местами. В NumPy эту операцию совершает функция transpose.

Будем работать с двумерным массивом:

In [53]:
arr = np.arange(8)
arr.shape = (2, 4)
arr

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

Транспонируем его:

In [54]:
arr_trans = arr.transpose()
arr_trans

array([[0, 4],
       [1, 5],
       [2, 6],
       [3, 7]])

При транспонировании одномерного массива его форма не меняется:

In [56]:
arr = np.arange(3)
print(arr.shape)
arr_trans = arr.transpose()
print(arr_trans.shape)

(3,)
(3,)


            ИНДЕКСЫ И СРЕЗЫ В МАССИВАХ

В определении массива указано, что он позволяет быстро получать элементы по индексу. Как же это происходит?

Создадим массив из шести чисел:

In [57]:
arr = np.linspace(1,2,6)
arr

array([1. , 1.2, 1.4, 1.6, 1.8, 2. ])

Обратиться к его элементу по индексу можно так же, как и к списку:

In [58]:
print(arr[2])

1.4


Привычная запись для срезов работает и для одномерных массивов:

In [59]:
print(arr[2:4])

[1.4 1.6]


Наконец, напечатать массив в обратном порядке можно с помощью привычной конструкции [::-1]:

In [60]:
print(arr[::-1])

[2.  1.8 1.6 1.4 1.2 1. ]


С многомерными массивами работать немного интереснее. Создадим двумерный массив из одномерного:

In [63]:
nd_array = np.linspace(0,6,12,  endpoint=False).reshape(3,4)
nd_array

array([[0. , 0.5, 1. , 1.5],
       [2. , 2.5, 3. , 3.5],
       [4. , 4.5, 5. , 5.5]])

Можно воспользоваться привычной записью нескольких индексов в нескольких квадратных скобках:

In [64]:
nd_array[1][2]

3.0

Как видите, получилось то же самое число. Также через запятую можно передавать срезы или даже их комбинации с индексами. Например, получим все элементы из колонки 3 для первых двух строк:

In [65]:
nd_array[:2, 2]

array([1., 3.])

Несмотря на то что в массиве этот срез является столбцом, вместо него мы получили одномерный массив в виде строки.

Можно применять срезы сразу и к строкам, и к столбцам:

In [66]:
nd_array[1:, 2:4]

array([[3. , 3.5],
       [5. , 5.5]])

Чтобы получить все значения из какой-то оси, можно оставить на её месте двоеточие. Например, из всех строк получим срез с третьего по четвёртый столбцы:

In [67]:
nd_array[:, 2:4]

array([[1. , 1.5],
       [3. , 3.5],
       [5. , 5.5]])

Чтобы получить самую последнюю ось (в данном случае все столбцы), двоеточие писать необязательно. Строки будут получены целиком по умолчанию:

In [68]:
nd_array[:2]

array([[0. , 0.5, 1. , 1.5],
       [2. , 2.5, 3. , 3.5]])